### ISSUE TITLE
when trying to login with google (ckboard account), Error occurs

### ISSUE THREAD

**Issue by SeongwoonHong** [ck-board/ck-board#87]
<img width="1067" alt="screen shot 2018-03-03 at 1 15 38 am" src="https://user-images.githubusercontent.com/19713918/36931278-7c48059e-1e80-11e8-8c9f-12a9fd32a4b2.png">
![screen shot 2018-03-03 at 1 15 45 am](https://user-images.githubusercontent.com/19713918/36931287-c0e7a29a-1e80-11e8-9e23-80113f8cf290.png)

After this happens, If I re-type URL of Home or other pages, I can see that I have successfully logged in

**Comment by lyndonoc** [comment]
fixed in staging, closing
